--- drop all tables if they exist
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS addr CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS bank_accounts CASCADE;
DROP TABLE IF EXISTS author CASCADE;
DROP TABLE IF EXISTS publisher CASCADE;
DROP TABLE IF EXISTS book CASCADE;
DROP TABLE IF EXISTS store_items CASCADE;
DROP TABLE IF EXISTS store_item_history CASCADE;
DROP TABLE IF EXISTS featured_items CASCADE;
DROP TABLE IF EXISTS email_request CASCADE;

CREATE TABLE users (
    id integer generated by default as identity primary key,
    email varchar(255) unique,
    pw_hash varchar(255),
    super_user boolean DEFAULT False
);

CREATE TABLE addr (
    id integer generated by default as identity primary key,
    country varchar(127),
    province varchar(63),
    city varchar(255),
    address text
);

CREATE TABLE orders (
    id integer generated by default as identity primary key,
    total_price integer,
    total_discount_price integer,
    cart jsonb,
    first_name text,
    last_name text,
    tracking varchar(64),
    b_address_id integer references addr(id),
    s_address_id integer references addr(id),
    order_date timestamp,
    user_id integer references users(id)
);

CREATE TABLE bank_accounts (
    id integer generated by default as identity primary key,
    balance integer default 0
);

CREATE TABLE author (
    id integer generated by default as identity primary key,
    source_key text,
    name text
);

CREATE TABLE publisher (
    id integer generated by default as identity primary key,
    name text,
    address_id integer references addr(id),
    banking_account_id integer references bank_accounts(id)
);

CREATE TABLE book (
    id integer generated by default as identity primary key,
    source_key text,
    name text,
    author_id integer references author(id),
    publisher_id integer references publisher(id),
    isbn text,
    page_count integer,
    description text,
    genre text
);

CREATE TABLE store_items (
    id integer generated by default as identity primary key,
    ref_id integer,
    item_type smallint,
    name text,
    quantity int,
    price int,
    discount_price int,
    revenue_share_percent numeric(3, 2),
    auto_order_threshold int,
    img_file_name text default 'default.jpg'
);

CREATE TABLE store_item_history (
    store_item_id integer references store_items(id),
    order_id integer references orders(id),
    amount integer,
    owner_share integer,
    publisher_share integer,
    PRIMARY KEY (store_item_id, order_id)
);

CREATE TABLE featured_items (
    id integer primary key
);

--- To show that our email trigger works
CREATE TABLE email_request (
    amount integer,
    publisher_id integer,
    email_date timestamp primary key
);