CREATE TABLE users (
    id integer generated by default as identity primary key,
    email varchar(255),
    pw_hash varchar(255)
);

CREATE TABLE addr (
    id integer generated by default as identity primary key,
    country varchar(127),
    province varchar(63),
    city varchar(255),
    address text
);

CREATE TABLE orders (
    id integer generated by default as identity primary key,
    cart jsonb,
    first_name text,
    last_name text,
    tracking varchar(64),
    b_address_id integer,
    s_address_id integer
);